version: '3'

services:
  web:
    build: ./docker/web/
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: offshoa_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: secret
    ports:
      - 5435:5432
    volumes:
      - pgsql-data:/var/lib/pgsql

volumes:
  pgsql-data:
